# Generated by Django 5.0.6 on 2024-06-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название маршрута')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(blank=True, max_length=100, verbose_name='Начальная станция')),
                ('end_point', models.CharField(blank=True, max_length=100, verbose_name='Конечная станция')),
                ('departure_time', models.TimeField(verbose_name='Начало движения')),
                ('arrival_time', models.TimeField(verbose_name='Окончание движения')),
                ('interval', models.IntegerField(verbose_name='Интервал движения')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.route')),
            ],
        ),
    ]
