# Generated by Django 5.0.6 on 2024-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_point',
            field=models.CharField(max_length=100, verbose_name='Конечная станция'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_point',
            field=models.CharField(max_length=100, verbose_name='Начальная станция'),
        ),
    ]
